site:
  about:
    siteName: Camunda BPM Taskpool
    siteDescription: A component for pooling Camunda BPM user tasks with business data for high performance queries.
    avatar: 'assets/media/favicon.png'

allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'prism'
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'kotlin'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'


services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'zambrovski'
        repo: 'holunda-io/camunda-bpm-taskpool'
