version: "3.5"

networks:
  taskpool-net:
    name: taskpool

volumes:
  postgres-data:
    external: true
  axonserver-data:
    external: true
  mongo-data:
    external: true

services:
  postgres:
    image: postgres:9
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=s3cr3T!
    volumes:
      - ./.docker/postgresql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - taskpool-net

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    ports:
      - 8024:8024
      - 8124:8124
    volumes:
      - axonserver-data:/opt/axonserver/data
    networks:
      - taskpool-net
    environment:
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
      AXONIQ_AXONSERVER_SSL_ENABLED: "false"
      AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED: "false"
      AXONIQ_AXONSERVER_NAME: "localhost"
      AXONIQ_AXONSERVER_HOSTNAME: "localhost"
      AXONIQ_AXONSERVER_AUTOCLUSTER_FIRST: "localhost"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./.docker/mongodb-conf:/etc/mongo
      - ./.docker/mongodb-init:/docker-entrypoint-initdb.d/
    command:
      - "--config"
      - "/etc/mongo/mongod.conf"
      - "--wiredTigerCacheSizeGB"
      - "0.5"
    networks:
      - taskpool-net


